### ISSUE TITLE
How to use the Attribute __new__ method 

### ISSUE THREAD

**Issue by Toadman30** [markreidvfx/pyavb#13]
Hi I'm trying to create an Attribute Class with a list of items. When I do a dump I have an Attribute called _USER which are the user columns. Within it there is another Attribute with a list of items. How can I recreate that list, attach it to an Attribute class and set it to the _USER? When I use `__setitem__` I can not set the value to a list. So i'm guessing I need to create a new Attribute using the` __new__` method. I'm not sure how this method works so I was hoping you could give an example.

Here is the outcome I am looking for. _USER Attributes([('Sort', '143'), ('Turnover Notes', 'New')])

**Comment by markreidvfx** [comment]
I haven't tested yet but I think you use the factory on the root file object. Something like `file.create.Attributes()`. It should call `__new__` and run `__init__` .

**Comment by Toadman30** [comment]
That did it, thank you.

Some code incase someone else gets suck.

```
new_mob_att = f.create.Attributes()
new_mob_att['Turnover Notes'] = ''
new_mob_att['Clip Name Copy'] = clip_name
new_mob_att['Head Handle'] = '32'
new_mob_att['Tail Handle'] = '32'

mob.attributes['_USER'] = new_mob_att
```
