### ISSUE TITLE
Subclips in a Bin

### ISSUE THREAD

**Issue by Toadman30** [markreidvfx/pyavb#15]
Hi,

I was wondering if there was a way to return only the subclips within a bin and not everything on a timeline? I have a bin that has a few supclips and a seq but running mastermobs() or compositionmobs() returns everything that is on the timeline along with everything within the bin.

**Comment by markreidvfx** [comment]
If it is like AAF, then subclips are CompositionMobs with `compositionmob.usage == 'subclip'`
