### ISSUE TITLE
Is it possible to use pyavb to copy bins / change the mob ID

### ISSUE THREAD

**Issue by communque** [markreidvfx/pyavb#17]
The goal would be to copy the bin (capturing the contents and active bin view) by presumably changings its mob id (or whatever it takes) to escape the error "Unable to open file "BinName2" / Exception: A copy named "BinName1" is already open"

If so, how so?  (New to pyavb.  Curious what it's capable of)

**Comment by markreidvfx** [comment]
You can change the bin's uid like this 

```python
with avb.open("path/to/bin.avb") as f:
    f.content.uid = avb.utils.generate_uid()
    f.write("path/to/new_bin.avb")
```

**Comment by communque** [comment]
Brilliant!  Thank you!!
