### ISSUE TITLE
Avb adapter for OpenTimelineIO?

### ISSUE THREAD

**Issue by tin2tin** [markreidvfx/pyavb#2]
Have you considered using this project as a stepping stone for coding a avb adapter for the Opentimelineio project: https://opentimelineio.readthedocs.io/en/latest/tutorials/write-an-adapter.html which will allow converting avb files to common formats like aaf, edl and fcpxml with ease?

**Comment by markreidvfx** [comment]
Yes I have, it would be awesome, but just haven't found the time to look into it due other projects.  Pull request are most welcome :p

The best starting point for this is to look at  [avb2aaf.py](https://github.com/markreidvfx/pyavb/blob/master/examples/avb2aaf.py)
The data structure is very similar to AAF. OpentimelineIO is still working on their AAF adapter, but it would be good ref as well.

**Comment by markreidvfx** [comment]
an adapter has been started here
https://github.com/markreidvfx/otio-avb-adapter
