### ISSUE TITLE
The future of coatldev/six:latest

### ISSUE THREAD

**Issue by cesarcoatl** [markreidvfx/pyavb#22]
Hello there,

I am the maintainer for coatldev/six and first, I'd like to thank you for using that image. Secondly, I would like to share my decision behind the future of the `latest` tag for that image.

coatldev/six was created because I had the need to test my packages were properly installed on Python 2, and running tests code formatters, linters and type checking using Python 3.10 because `mypy[python2]==0.971` when 3.11.0 was released, it could not be installed, but recent tests show that it is now possible to install using 3.11 and even 3.12.0rc2.

Because of those reasons, coatldev/six is no longer exclusively for Python 3.10 and 2.7; it now has 3.11 and 3.12 as options, too. ~~So a `latest` tag does not make sense anymore.~~

By looking at your CI workflow, if I may, I would suggest using the [`2.7`](https://hub.docker.com/_/python/tags?page=1&name=2.7) tag of the official image, e.g., `python:2.7`, `python:2.7-alpine`, or `python:2.7-slim`. These are smaller images and Python 2-specific which might decrease runtime of your CI workflow.

~~I plan to completely remove the `latest` tag by the end of October or whenever this has been updated on this repo.~~

____
EDIT

On a second thought, I have considered keeping the `latest` tag but it will be pointing to the latest stable release for Python 3, which will be 3.12.0 whenever it is released this October.

In the meantime, `latest` will keep pointing to `coatldev/six:3.10.13`. But at the end of September it will be pointing to `coatldev/six:3.11`.

PR https://github.com/coatl-dev/docker-six/pull/24 has been merged.

This means that if we get a 3.11.6 release before 3.12.0, we will have the following tags for it: `3`, `3.11`, `3.11.6`, and `latest`.

Regards,
César

**Comment by markreidvfx** [comment]
Thanks for reaching out to me about this, I really appreciate it!
I'm not very knowledgeable about docker and didn't even know python had official images!
I'll switch to using them.
