### ISSUE TITLE
building a group clip from master clips and syncing

### ISSUE THREAD

**Issue by russellaugust** [markreidvfx/pyavb#7]
first off, this library is amazing.  it opens up so many avenues to help workflow at my post house.

Digging through the code, I get the impression it may be possible to create group clips, subclips or sync audio from master clips.  Since you built it, I figure you could answer that question before I dig too far down the rabbit hole.

**Comment by russellaugust** [comment]
From what I'm seeing, group clips are referred to as SELECTORS?

**Comment by markreidvfx** [comment]
yes, groupclips I believe are called selectors, I sometimes used the AAF names for objects. It is definitely possible to do what you are describing, the module can write any AVB object that I've been able to document. It might take a lot of trial and error to get it working. The best way is to match the structure of a file that does what you want and start from there.

**Comment by russellaugust** [comment]
@markreidvfx do you know what the `left_bob` and `right_bob` are? Trying to trace it back and understand what it is but found much.  I was thinking it was referencing the BOBPosition and had to do with the composition's in/out boundaries but it always seems to return None.

**Comment by markreidvfx** [comment]
Maybe this helps, that's how I've been able to translate it to a AAF selector
https://github.com/markreidvfx/pyavb/blob/master/examples/avb2aaf.py#L335

I'm not entirely sure what the Bob data ref is, I think is some legacy OMF thing. I thought it might be in the original OMF spec, but I've been unable to find it anywhere. My guess was Bob means, bytes of binary or bag of bits. Left and right could be some sort of linked list structure, but I don't know.

The XML representation of a bin file calls it 
__OMFI:CPNT:LeftBob

**Comment by communque** [comment]
@russellaugust Any luck with this?

**Comment by russellaugust** [comment]
No luck yet unfortunately. It's pretty complicated as far as I can tell.

**Comment by communque** [comment]
@russellaugust Thanks for the followup. Complicated no doubt.
So far I've been able to change the sync of items contained in a group clip.  That part seems easy.
No luck adding clips though, not yet at least.

**Comment by russellaugust** [comment]
I'll be digging deeper into this as well over the coming months, so I'll share any of my findings. Let me know what you find.
